version: '3.1'

services:

  fastcampus-docker-mysql:
    image: mysql:8.3
    volumes:
      - ./data/legacy-db:/var/lib/mysql
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE : legacy-ad

  fastcampus-docker-postgres:
    image: postgres:16.2
    volumes:
      - ./data/recent-db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 1234

  fastcampus-docker-rabbitmq:
    image: rabbitmq:3.13.1-management
    ports:
      - "5673:5672"
      - "15673:15672"

    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: legacy